// Generated by gencpp from file hsr_common_pkg/ObjRecFeedback.msg
// DO NOT EDIT!


#ifndef HSR_COMMON_PKG_MESSAGE_OBJRECFEEDBACK_H
#define HSR_COMMON_PKG_MESSAGE_OBJRECFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hsr_common_pkg
{
template <class ContainerAllocator>
struct ObjRecFeedback_
{
  typedef ObjRecFeedback_<ContainerAllocator> Type;

  ObjRecFeedback_()
    : obj_rec_feedback(false)  {
    }
  ObjRecFeedback_(const ContainerAllocator& _alloc)
    : obj_rec_feedback(false)  {
  (void)_alloc;
    }



   typedef uint8_t _obj_rec_feedback_type;
  _obj_rec_feedback_type obj_rec_feedback;




  typedef boost::shared_ptr< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ObjRecFeedback_

typedef ::hsr_common_pkg::ObjRecFeedback_<std::allocator<void> > ObjRecFeedback;

typedef boost::shared_ptr< ::hsr_common_pkg::ObjRecFeedback > ObjRecFeedbackPtr;
typedef boost::shared_ptr< ::hsr_common_pkg::ObjRecFeedback const> ObjRecFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hsr_common_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'hsr_common_pkg': ['/home/guest/athome_ws/devel/share/hsr_common_pkg/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ccbdee7c4f9e6f0f3dedd5d54715160";
  }

  static const char* value(const ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ccbdee7c4f9e6f0ULL;
  static const uint64_t static_value2 = 0xf3dedd5d54715160ULL;
};

template<class ContainerAllocator>
struct DataType< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hsr_common_pkg/ObjRecFeedback";
  }

  static const char* value(const ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool obj_rec_feedback\n\
\n\
";
  }

  static const char* value(const ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obj_rec_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjRecFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hsr_common_pkg::ObjRecFeedback_<ContainerAllocator>& v)
  {
    s << indent << "obj_rec_feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obj_rec_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HSR_COMMON_PKG_MESSAGE_OBJRECFEEDBACK_H
