// Generated by gencpp from file hsr_common_pkg/SpeechRecGoal.msg
// DO NOT EDIT!


#ifndef HSR_COMMON_PKG_MESSAGE_SPEECHRECGOAL_H
#define HSR_COMMON_PKG_MESSAGE_SPEECHRECGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hsr_common_pkg
{
template <class ContainerAllocator>
struct SpeechRecGoal_
{
  typedef SpeechRecGoal_<ContainerAllocator> Type;

  SpeechRecGoal_()
    : speech_rec_goal()  {
    }
  SpeechRecGoal_(const ContainerAllocator& _alloc)
    : speech_rec_goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _speech_rec_goal_type;
  _speech_rec_goal_type speech_rec_goal;




  typedef boost::shared_ptr< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechRecGoal_

typedef ::hsr_common_pkg::SpeechRecGoal_<std::allocator<void> > SpeechRecGoal;

typedef boost::shared_ptr< ::hsr_common_pkg::SpeechRecGoal > SpeechRecGoalPtr;
typedef boost::shared_ptr< ::hsr_common_pkg::SpeechRecGoal const> SpeechRecGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hsr_common_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'hsr_common_pkg': ['/home/guest/athome_ws/devel/share/hsr_common_pkg/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b6bf800318b350fcfba951224e46594";
  }

  static const char* value(const ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b6bf800318b350fULL;
  static const uint64_t static_value2 = 0xcfba951224e46594ULL;
};

template<class ContainerAllocator>
struct DataType< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hsr_common_pkg/SpeechRecGoal";
  }

  static const char* value(const ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string speech_rec_goal\n\
";
  }

  static const char* value(const ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speech_rec_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechRecGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hsr_common_pkg::SpeechRecGoal_<ContainerAllocator>& v)
  {
    s << indent << "speech_rec_goal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.speech_rec_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HSR_COMMON_PKG_MESSAGE_SPEECHRECGOAL_H
