; Auto-generated. Do not edit!


(cl:in-package hsr_common_pkg-msg)


;//! \htmlinclude ObjRecFeedback.msg.html

(cl:defclass <ObjRecFeedback> (roslisp-msg-protocol:ros-message)
  ((obj_rec_feedback
    :reader obj_rec_feedback
    :initarg :obj_rec_feedback
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ObjRecFeedback (<ObjRecFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjRecFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjRecFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hsr_common_pkg-msg:<ObjRecFeedback> is deprecated: use hsr_common_pkg-msg:ObjRecFeedback instead.")))

(cl:ensure-generic-function 'obj_rec_feedback-val :lambda-list '(m))
(cl:defmethod obj_rec_feedback-val ((m <ObjRecFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hsr_common_pkg-msg:obj_rec_feedback-val is deprecated.  Use hsr_common_pkg-msg:obj_rec_feedback instead.")
  (obj_rec_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjRecFeedback>) ostream)
  "Serializes a message object of type '<ObjRecFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'obj_rec_feedback) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjRecFeedback>) istream)
  "Deserializes a message object of type '<ObjRecFeedback>"
    (cl:setf (cl:slot-value msg 'obj_rec_feedback) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjRecFeedback>)))
  "Returns string type for a message object of type '<ObjRecFeedback>"
  "hsr_common_pkg/ObjRecFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjRecFeedback)))
  "Returns string type for a message object of type 'ObjRecFeedback"
  "hsr_common_pkg/ObjRecFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjRecFeedback>)))
  "Returns md5sum for a message object of type '<ObjRecFeedback>"
  "0ccbdee7c4f9e6f0f3dedd5d54715160")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjRecFeedback)))
  "Returns md5sum for a message object of type 'ObjRecFeedback"
  "0ccbdee7c4f9e6f0f3dedd5d54715160")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjRecFeedback>)))
  "Returns full string definition for message of type '<ObjRecFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool obj_rec_feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjRecFeedback)))
  "Returns full string definition for message of type 'ObjRecFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool obj_rec_feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjRecFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjRecFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjRecFeedback
    (cl:cons ':obj_rec_feedback (obj_rec_feedback msg))
))
