; Auto-generated. Do not edit!


(cl:in-package hsr_common_pkg-msg)


;//! \htmlinclude ObjRecResult.msg.html

(cl:defclass <ObjRecResult> (roslisp-msg-protocol:ros-message)
  ((obj_rec_result
    :reader obj_rec_result
    :initarg :obj_rec_result
    :type cl:integer
    :initform 0))
)

(cl:defclass ObjRecResult (<ObjRecResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ObjRecResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ObjRecResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hsr_common_pkg-msg:<ObjRecResult> is deprecated: use hsr_common_pkg-msg:ObjRecResult instead.")))

(cl:ensure-generic-function 'obj_rec_result-val :lambda-list '(m))
(cl:defmethod obj_rec_result-val ((m <ObjRecResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hsr_common_pkg-msg:obj_rec_result-val is deprecated.  Use hsr_common_pkg-msg:obj_rec_result instead.")
  (obj_rec_result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ObjRecResult>) ostream)
  "Serializes a message object of type '<ObjRecResult>"
  (cl:let* ((signed (cl:slot-value msg 'obj_rec_result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ObjRecResult>) istream)
  "Deserializes a message object of type '<ObjRecResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'obj_rec_result) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ObjRecResult>)))
  "Returns string type for a message object of type '<ObjRecResult>"
  "hsr_common_pkg/ObjRecResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ObjRecResult)))
  "Returns string type for a message object of type 'ObjRecResult"
  "hsr_common_pkg/ObjRecResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ObjRecResult>)))
  "Returns md5sum for a message object of type '<ObjRecResult>"
  "3a7d7b9d4ca1f9210f5a4bf45791d0c9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ObjRecResult)))
  "Returns md5sum for a message object of type 'ObjRecResult"
  "3a7d7b9d4ca1f9210f5a4bf45791d0c9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ObjRecResult>)))
  "Returns full string definition for message of type '<ObjRecResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 obj_rec_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ObjRecResult)))
  "Returns full string definition for message of type 'ObjRecResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 obj_rec_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ObjRecResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ObjRecResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ObjRecResult
    (cl:cons ':obj_rec_result (obj_rec_result msg))
))
