; Auto-generated. Do not edit!


(cl:in-package hsr_common_pkg-msg)


;//! \htmlinclude SoundEffectGoal.msg.html

(cl:defclass <SoundEffectGoal> (roslisp-msg-protocol:ros-message)
  ((sound_effect_goal
    :reader sound_effect_goal
    :initarg :sound_effect_goal
    :type cl:string
    :initform ""))
)

(cl:defclass SoundEffectGoal (<SoundEffectGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoundEffectGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoundEffectGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hsr_common_pkg-msg:<SoundEffectGoal> is deprecated: use hsr_common_pkg-msg:SoundEffectGoal instead.")))

(cl:ensure-generic-function 'sound_effect_goal-val :lambda-list '(m))
(cl:defmethod sound_effect_goal-val ((m <SoundEffectGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hsr_common_pkg-msg:sound_effect_goal-val is deprecated.  Use hsr_common_pkg-msg:sound_effect_goal instead.")
  (sound_effect_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoundEffectGoal>) ostream)
  "Serializes a message object of type '<SoundEffectGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'sound_effect_goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'sound_effect_goal))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoundEffectGoal>) istream)
  "Deserializes a message object of type '<SoundEffectGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'sound_effect_goal) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'sound_effect_goal) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoundEffectGoal>)))
  "Returns string type for a message object of type '<SoundEffectGoal>"
  "hsr_common_pkg/SoundEffectGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoundEffectGoal)))
  "Returns string type for a message object of type 'SoundEffectGoal"
  "hsr_common_pkg/SoundEffectGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoundEffectGoal>)))
  "Returns md5sum for a message object of type '<SoundEffectGoal>"
  "a2a765b6b96ab9f3887ab341e6120474")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoundEffectGoal)))
  "Returns md5sum for a message object of type 'SoundEffectGoal"
  "a2a765b6b96ab9f3887ab341e6120474")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoundEffectGoal>)))
  "Returns full string definition for message of type '<SoundEffectGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string sound_effect_goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoundEffectGoal)))
  "Returns full string definition for message of type 'SoundEffectGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string sound_effect_goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoundEffectGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'sound_effect_goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoundEffectGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SoundEffectGoal
    (cl:cons ':sound_effect_goal (sound_effect_goal msg))
))
