; Auto-generated. Do not edit!


(cl:in-package hsr_common_pkg-msg)


;//! \htmlinclude SoundEffectFeedback.msg.html

(cl:defclass <SoundEffectFeedback> (roslisp-msg-protocol:ros-message)
  ((sound_effect_feedback
    :reader sound_effect_feedback
    :initarg :sound_effect_feedback
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SoundEffectFeedback (<SoundEffectFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoundEffectFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoundEffectFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hsr_common_pkg-msg:<SoundEffectFeedback> is deprecated: use hsr_common_pkg-msg:SoundEffectFeedback instead.")))

(cl:ensure-generic-function 'sound_effect_feedback-val :lambda-list '(m))
(cl:defmethod sound_effect_feedback-val ((m <SoundEffectFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hsr_common_pkg-msg:sound_effect_feedback-val is deprecated.  Use hsr_common_pkg-msg:sound_effect_feedback instead.")
  (sound_effect_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoundEffectFeedback>) ostream)
  "Serializes a message object of type '<SoundEffectFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'sound_effect_feedback) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoundEffectFeedback>) istream)
  "Deserializes a message object of type '<SoundEffectFeedback>"
    (cl:setf (cl:slot-value msg 'sound_effect_feedback) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoundEffectFeedback>)))
  "Returns string type for a message object of type '<SoundEffectFeedback>"
  "hsr_common_pkg/SoundEffectFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoundEffectFeedback)))
  "Returns string type for a message object of type 'SoundEffectFeedback"
  "hsr_common_pkg/SoundEffectFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoundEffectFeedback>)))
  "Returns md5sum for a message object of type '<SoundEffectFeedback>"
  "4f1ec008d648d1acbd06e847ba17ffed")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoundEffectFeedback)))
  "Returns md5sum for a message object of type 'SoundEffectFeedback"
  "4f1ec008d648d1acbd06e847ba17ffed")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoundEffectFeedback>)))
  "Returns full string definition for message of type '<SoundEffectFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool sound_effect_feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoundEffectFeedback)))
  "Returns full string definition for message of type 'SoundEffectFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool sound_effect_feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoundEffectFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoundEffectFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SoundEffectFeedback
    (cl:cons ':sound_effect_feedback (sound_effect_feedback msg))
))
