; Auto-generated. Do not edit!


(cl:in-package hsr_common_pkg-msg)


;//! \htmlinclude SoundEffectResult.msg.html

(cl:defclass <SoundEffectResult> (roslisp-msg-protocol:ros-message)
  ((sound_effect_result
    :reader sound_effect_result
    :initarg :sound_effect_result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SoundEffectResult (<SoundEffectResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoundEffectResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoundEffectResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hsr_common_pkg-msg:<SoundEffectResult> is deprecated: use hsr_common_pkg-msg:SoundEffectResult instead.")))

(cl:ensure-generic-function 'sound_effect_result-val :lambda-list '(m))
(cl:defmethod sound_effect_result-val ((m <SoundEffectResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hsr_common_pkg-msg:sound_effect_result-val is deprecated.  Use hsr_common_pkg-msg:sound_effect_result instead.")
  (sound_effect_result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoundEffectResult>) ostream)
  "Serializes a message object of type '<SoundEffectResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'sound_effect_result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoundEffectResult>) istream)
  "Deserializes a message object of type '<SoundEffectResult>"
    (cl:setf (cl:slot-value msg 'sound_effect_result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoundEffectResult>)))
  "Returns string type for a message object of type '<SoundEffectResult>"
  "hsr_common_pkg/SoundEffectResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoundEffectResult)))
  "Returns string type for a message object of type 'SoundEffectResult"
  "hsr_common_pkg/SoundEffectResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoundEffectResult>)))
  "Returns md5sum for a message object of type '<SoundEffectResult>"
  "d161aeed5b6d234a0b24e116c3947766")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoundEffectResult)))
  "Returns md5sum for a message object of type 'SoundEffectResult"
  "d161aeed5b6d234a0b24e116c3947766")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoundEffectResult>)))
  "Returns full string definition for message of type '<SoundEffectResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool sound_effect_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoundEffectResult)))
  "Returns full string definition for message of type 'SoundEffectResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool sound_effect_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoundEffectResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoundEffectResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SoundEffectResult
    (cl:cons ':sound_effect_result (sound_effect_result msg))
))
