; Auto-generated. Do not edit!


(cl:in-package hsr_common_pkg-msg)


;//! \htmlinclude SpeechRecFeedback.msg.html

(cl:defclass <SpeechRecFeedback> (roslisp-msg-protocol:ros-message)
  ((speech_rec_feedback
    :reader speech_rec_feedback
    :initarg :speech_rec_feedback
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass SpeechRecFeedback (<SpeechRecFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SpeechRecFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SpeechRecFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hsr_common_pkg-msg:<SpeechRecFeedback> is deprecated: use hsr_common_pkg-msg:SpeechRecFeedback instead.")))

(cl:ensure-generic-function 'speech_rec_feedback-val :lambda-list '(m))
(cl:defmethod speech_rec_feedback-val ((m <SpeechRecFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hsr_common_pkg-msg:speech_rec_feedback-val is deprecated.  Use hsr_common_pkg-msg:speech_rec_feedback instead.")
  (speech_rec_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SpeechRecFeedback>) ostream)
  "Serializes a message object of type '<SpeechRecFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'speech_rec_feedback) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SpeechRecFeedback>) istream)
  "Deserializes a message object of type '<SpeechRecFeedback>"
    (cl:setf (cl:slot-value msg 'speech_rec_feedback) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SpeechRecFeedback>)))
  "Returns string type for a message object of type '<SpeechRecFeedback>"
  "hsr_common_pkg/SpeechRecFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SpeechRecFeedback)))
  "Returns string type for a message object of type 'SpeechRecFeedback"
  "hsr_common_pkg/SpeechRecFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SpeechRecFeedback>)))
  "Returns md5sum for a message object of type '<SpeechRecFeedback>"
  "18e29516505e5c702a5f9e2e172510d6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SpeechRecFeedback)))
  "Returns md5sum for a message object of type 'SpeechRecFeedback"
  "18e29516505e5c702a5f9e2e172510d6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SpeechRecFeedback>)))
  "Returns full string definition for message of type '<SpeechRecFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#string[] speech_rec_feedback~%bool speech_rec_feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SpeechRecFeedback)))
  "Returns full string definition for message of type 'SpeechRecFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#string[] speech_rec_feedback~%bool speech_rec_feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SpeechRecFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SpeechRecFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SpeechRecFeedback
    (cl:cons ':speech_rec_feedback (speech_rec_feedback msg))
))
